LemmyNet/joinlemmy-site

- static/scripts/asyncapi.html
- static/scripts/asyncapi.yaml
Gradually building out from https://github.com/LemmyNet/lemmy-docs/blob/cf3236bb620048897048027d8cdff34401ad85ee/src/en/contributing/websocket_http_api.md
Also added an asyncapi.html file for a quick preview
> Added site publish and subscribe channels to asyncapi file

- static/scripts/asyncapi.yaml
Some responses have not yet been documented (due to issues with Docker container) - I will cycle back to these later.
aysncapi.yaml is now too big to display in the online AsyncAPI playground. However, asyncapi.yaml will show all the channels
> Added Community channels to asyncapi.yaml

- templates/join.html
I didnt notice that you added the instance with the wrong details. This is why you should make PRs ;)
> Fix diversa.social details

- deploy.sh
- src/shared/i18next.ts
Same as https://github.com/LemmyNet/lemmy-ui/pull/267/files
> Add check for unused languages in deploy.sh

- src/assets/scripts/asyncapi.yaml
> Update Asyncapi specification to follow Lukasz Gornicki's guidance

- src/assets/css/main.css
- src/shared/components/about.tsx
- src/shared/components/link-line.tsx
- src/shared/routes.ts
- update_submodules.sh
> Adding about page

- src/shared/components/contact.tsx
It would also make sense to change the email to contact at join-lemmy org
> Change Matrix contact link to Lemmy space, change Github link

- .drone.yml
> Fix drone cron build

- src/assets/news/2022-05-27 - Lemmy Release v0.16.4 - Peertube federation, Rust API and other improvements.md
Noticed that the date is specified twice in all files, first in the title and then right below in the "written by" line. Not sure whats the point of that.
> Release 0.16.4

- .drone.yml
For easier publishing of release announcements.
> Besides cron, also build new tags

- recommended-instances.json
Add feddit.it, remove forum.nobigtech.es which is completely inactive.
> Update recommended instances

- src/shared/i18next.ts
It's 100 % translated. You only have to pull the translation from Weblate.
> Show Esperanto translation

- .woodpecker.yml
This way translations should reach the website without doing anything manually.
> Use woodpecker git plugin including remote submodule update

- recommended-instances.json
> Replace jeremmy with sopuli as recommended instance

- src/shared/i18next.ts
I've already submitted all the required translations, on Weblate, I believe.
I hope this is all that's needed to add the language to the dropdown and all :)
> Add danish to languages

- recommended-instances.json
Probably needs [this PR](https://github.com/LemmyNet/joinlemmy-site/pull/150) first.
> Recommend feddit.dk when displaying in Danish

- recommended-instances.json
Added lemmy.world.
Lemmy.world is general purpose. The main language is English.
I am in the admin chat (@ruud:h-y-p-e-r.space)
In case of a large influx, we can scale. I did the same with mastodon.world during the November/December influxes.
> Update recommended-instances.json : Added lemmy.world

- recommended-instances.json
Its already the second largest instance
> Remove beehaw.org from recommendations

- recommended-instances.json
> add bakchodi.org to exclude list

- Dockerfile
- src/shared/components/link-line.tsx
- src/shared/components/main.tsx
- src/shared/utils.ts
https://github.com/LemmyNet/lemmy-docs/pull/223
> Remove docs translations

- .gitmodules
- Dockerfile
I tested this locally, it looks good.
> Upgrading lemmy-js-client to use the new docs.

- src/shared/components/instances.tsx
- src/shared/components/link-line.tsx
This seems more inviting, as its not necessary to create an account before browsing the content
Requires https://github.com/LemmyNet/joinlemmy-translations/pull/18
> Change instance list buttons from "join" to "browse"

- src/shared/components/apps.tsx
Mlem dev here.  We had to update our TestFlight link so here is the new one!
> Updated Mlem TestFlight link

- recommended-instances.json
Its already very large and overloaded
> Remove lemmy.world from recommendations

- src/shared/components/apps.tsx
Hi,
A div closed in the wrong place so the page was a bit messy, corrected it.
> fix: corrected grid of webapps and cli apps not displaying correctly

- recommended-instances.json
- It's a general purpose instance
- It's well maintained and moderated
- Active part of Fediseer chain of trust
- Has clearly defined [rules](https://lemmings.world/post/1112) and [code of conduct](https://lemmings.world/post/1127)
> Add lemmings.world to recommended instances

- src/shared/components/instances-definitions.ts
> Update instances-definitions.ts - lemmy.myserv.one

- src/shared/components/instances-definitions.ts
> Add leminal.space to instances-definitions.ts

- src/assets/news/2023-10-31 - Join-Lemmy Redesign and Funding Drive.md
36k active users refers to monthly, not daily.
> Fix active user count in news

- src/shared/components/instances-definitions.ts
Adds the general/meme instance https://lemmy.best
> add lemmy.best instance to instances-definitions.ts

- src/shared/components/instances-definitions.ts
Added server topic and language for https://lemdro.id.
Thanks!
> Add lemdro.id instance definition

- src/shared/components/instances-definitions.ts
Add fanaticus.social to instance definition and add sports as its topic
> Add fanaticus.social instance to instances-definitions.ts

- src/shared/components/instances-definitions.ts
Adds roleplay.forum with all relevant information
> add rollenspiel.forum

- src/assets/lemmy_federation_context.json
I moved this directly into the Lemmy context for better compatibility, so no need to have it here.
https://github.com/LemmyNet/lemmy/pull/4302/commits/f7299e8c84736ad79fb8d6f2afc9f2a79edd52de
> Remove main activitypub context

- src/assets/lemmy_federation_context.json
Context [must be in "@context" field](https://www.w3.org/TR/json-ld11-api/#overview).
> Fix context definition in lemmy_federation_context.json

- src/shared/components/app-definitions.ts
- src/shared/components/apps.tsx
> Add third party tools

- update_donations.mjs
> Fixing donation package.

- src/shared/components/instances-definitions.ts
we were instructed to submit a PR to add topics.
> add lemmy.autism.place to recommended sites

- src/assets/lemmy_federation_context.json
Fix https://github.com/LemmyNet/lemmy/issues/5073
> Add ActivityStream alias to main context

- src/shared/components/navbar.tsx
> Fixing navbar dropdown.

- Dockerfile
https://github.com/nodejs/corepack/issues/612
> Using different corepack install method to fix corepack bug.

- src/shared/components/instances-definitions.ts
Added Bulgarian instance to instances-definitions.ts.
Related to [issue](https://github.com/LemmyNet/joinlemmy-site/issues/458).
> Added Bulgarian instance to instances-definitions.ts

- src/shared/components/app-definitions.ts
Summit for Lemmy is now open source.
> Update the app info for Summit for Lemmy

- src/assets/lemmy_federation_context.json
> Add as:Hashtag to context.json

- src/shared/components/app-definitions.ts
- src/shared/donation_stats.ts
These havent received any commit in the last two years.
> Remove unmaintained apps

- src/shared/components/app-definitions.ts
I recently created https://getvoyager.app
> Update voyager link

- src/shared/components/donate.tsx
- src/shared/components/main.tsx
- tailwind.config.js
> Add donate button on homepage

- package.json
- src/shared/components/navbar.tsx
> Larger menu size for mobile

- eslint.config.mjs
- package.json
- pnpm-lock.yaml
- update_donations.mjs
I already updated the `update.sh` script on our server with the correct env var API token, so once this merges, it should be working.
> Fixing patreon fetch

- src/shared/components/donate.tsx
Was playing around with it and noticed that the color always remained red.
> Fix percent calculation

- src/shared/components/donate-definitions.ts
There is no api so this needs to be updated manually
> Add donation stats for ko-fi

- src/shared/components/donate.tsx
We can do it like this so its intuitive. Needs better colors and css before merging though.
> Indicate preferred donation option (fixes #486)
