static/scripts/asyncapi.yaml

- I've been a little over-agressive in applying DRY (don't repeat yourself) principles using $ref so will review and soften the approach to make the English read more logically for the various use cases of any $ref references
- Some things I couldn't test on the public servers since admin or other elevated level was required (my local Docker image fell over and I've been struggling to get a new one working). I will try to re-install and come back to those. All these items are denoted by a # COMMENT line
- CreateSite - couldn't set up a 'virgin' server to test this so the response has not been documented
- LockPost - Could not form correct request using documented fields (even replacing edit_id with post_id or id)
- Needs a complete run-through to validate all requests and responses to …

Added Comment channels - initial pass of AsyncAPI file complete

---

static/scripts/asyncapi.yaml

Not all of it seemed entirely pertinent to the aims of an 'API quick start' which is what an API spec is (in documentation terms).
I have added references to the omitted parts (plus the installation guide).
I can edit websocket_http_api.md to remove things that sit in the AsyncAPI file if you wish. It could also do with a prominent link to the AsyncAPI file but not sure how your build process will render that...

Added information from https://join.lemmy.ml/do… … dfd438a …cs/en/contributing/websocket_http_api.html

---

src/assets/scripts/asyncapi.yaml

Most API responses generate an immediate and direct (synchronous) response to to the preceding API request: one of an error or a success response. However, for the ‘join’ requests (CommunityJoin, ModJoin, PostJoin, UserJoin), you can also receive any of several ‘as it happens’ (asynchronous) responses.
I’ve updated the API to catch some of these potential responses. Please extend to add any others:
- CommunityJoin - allowed CreatePost, EditPost, DeletePost, CreatePostLike responses
- PostJoin - allowed CreateComment, EditComment, DeleteComment, CreatePostLike responses
- UserJoin - allowed CreateCommentLike, CreateComment, CreatePrivateMessage, DeleteComment
ModJoin needs filling in, Feel free to add any others that apply to the others, too. For instance RemovePost and the like
In all …

Added asynchronous responses to Join requests

---

src/assets/scripts/asyncapi.yaml

Although my VSC linter didn't spot an error, the AsyncAPI generator did not like 'anyOf' - reverting to 'oneOf' fixes this.

Reverted anyOf to oneOf

---

src/shared/components/apps.tsx

Lemmur transferred to a separate org dedicated to lemmur (due to some permission limitations when under a private account + easier to grow). This PR updates references to the old repo.

Change lemmur repo links

---

src/shared/components/instances.tsx

I added an i18n joinlemmy-translations string for this. Unfortunately the css framework I'm using doesn't have a warning or yellow type thing, so I just used a default. I could hack that in if you think its really necessary.
Looks like:

Require applications

---

src/assets/css/main.css
src/client/index.tsx
src/server/index.tsx
src/shared/components/navbar.tsx
src/shared/i18next.ts
yarn.lock

There are probably better ways to implement some things, but its not easy to find good docs for js/ts.

Add language selector on site (fixes #64)

---

.drone.yml
generate_translations.mjs
src/shared/components/instances.tsx

This adds a separate list of "recommended instances" at the top of the instance list. This seems useful because most users only look at the first few items in the list, which are by definition very large instances that dont need new users. It also allows us to promote general-purpose instances, as opposed to "extremist" instances like lemmygrad.ml which is currently at the top.
The actual recommendations are still up for debate, i just picked two for testing now.
Still need to update localization strings.

Add recommended instances

---

.drone.yml

It seems like drone.io considers the `when` conditions using `and`, with no way to change to `or`. So these crawl/publish steps are never actually run ([see here](https://drone.yerbamate.ml/LemmyNet/joinlemmy-site/341/1/5)). Separating them like this should fix the problem.

Fix nightly builds

---

src/shared/components/instances.tsx

I also had to remove numToSI() call to make plurals work. There might be other places where plurals arent handled correctly.
https://www.i18next.com/translation-function/plurals

Use single string to translate active users per month (fixes #112)

---

src/shared/components/instances.tsx

I think this makes more sense, because we also show monthly users for each instance.
https://github.com/LemmyNet/joinlemmy-translations/pull/4

Show monthly active users in instance totals

---

.gitmodules
update_submodules.sh

The docs now use a hardcoded chose branch for the lemmy-js-client. This should avoid people using API abilities that haven't been released yet, simply because they've been merged into the main branch.

Use specific lemmy js client version

---

src/shared/components/apps.tsx
src/shared/components/contact.tsx
src/shared/components/donate.tsx
src/shared/components/instances.tsx
src/shared/components/main.tsx

Fixes #143
By the way, there are two translation keys I think aren't used: `about_title` and `sponsors_title`.

Fix <title> not being translated

---

src/shared/components/contact.tsx

People are using it for basic support which should go through other channels

Remove email address from contact page

---

src/shared/components/instances.tsx

Instances shouldnt be listed if signups are closed.
Also added a filter so that instances with less than 5 users are not listed. The specific number is debatable but it doesnt make much sense to list inactive instances.

Dont list instances with closed signups or few active users

---

Dockerfile

Kept failing with `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`. This change fixes it.
https://stackoverflow.com/a/59572966

Increase memory for Docker prod build

---

recommended-instances.json

Hey! I would like to propose lemm.ee as a recommended instance.
We have 80 users so far. We have some simple rules in the sidebar and there is an introductory post here: https://lemm.ee/post/26
Sign-ups are open and community creation is enabled for all users.

Add lemm.ee to recommended instances

---

src/shared/components/instances.tsx

Especially now that the number of users isn't displayed, I think this may spread the load a bit. My assumption is that tiny instances that barely make it on to the list are not ready for a huge influx of users, so putting them at the very top isn't a good idea. Instead I sort by a semi-random value weighted by active users such that the top displayed instances still tend to be the larger ones.

Make the order of popular instances semi-randomized

---

src/assets/news/2023-06-23 - Lemmy Release v0.18.0.md

Updated references to the old matrix channel to be to https://matrix.to/#/#lemmy-admin-support-topics:discuss.online instead.
I've updated the Matrix link to use the new Space to help people find the correct support.
Relates to:
https://github.com/LemmyNet/lemmy/pull/3599
https://github.com/LemmyNet/lemmy-docs/pull/248

Updated Lemmy Matrix Support link

---

src/shared/components/instances.tsx

The link hasn't been updated for over a month and I think it actively hurts new users when they click for example VLemmy, which no longer exists, as the 2nd most recommended instance.

Remove a no longer updated link

---

src/shared/components/instances.tsx

The intentional [update freeze](https://github.com/maltfield/awesome-lemmy-instances/issues/26) has ended after a ~4-week grace period has passed allowing instance admins to upgrade after the [breaking changes](https://github.com/LemmyNet/lemmy-stats-crawler/issues/9#issuecomment-1611991067) to lemmy-stats-crawler.
* https://github.com/maltfield/awesome-lemmy-instances/issues/26
* https://github.com/LemmyNet/joinlemmy-site/pull/227
The [Awesome Lemmy Instances](https://github.com/maltfield/awesome-lemmy-instances/) repo has been set back to update itself every 1 hour.

adding back 'awesome-lemmy-instances' after freeze ended

---

src/shared/components/apps.tsx

The main repo for `go-lemmy` is on my Gitea instance. This PR updates the URL for go-lemmy to the correct URL.

Update go-lemmy URL

---

recommended-instances.json

Another sus instance showed up. [People have found a bunch of "minor attracted person" stuff on that instance](https://sh.itjust.works/post/6400367), so this should definitely be excluded.

Exclude pedo instance

---

src/shared/components/instances-definitions.ts

Following the instructions in [this news](https://join-lemmy.org/news/2023-10-31_-_Join-Lemmy_Redesign_and_Funding_Drive), this adds the server language and server topic for my instance https://dormi.zone.

Add dormi.zone to instances-definitions.ts

---

.gitmodules

Necessary so that the new joinlemmy-site will pick up the new API changes.

Upgrade to lemmy js client 019

---

Dockerfile
generate_rss_feed.mjs
package.json
src/assets/images/rss.svg
src/server/index.tsx
src/shared/components/main.tsx
src/shared/components/news.tsx
yarn.lock

Fixes issue #96 @Nutomic 
An RSS feed for join-lemmy.org news. I took a very pragmatic approach and used JavaScript for it. It parses the markdown news files and generates RSS feed items out of it. During the container build, it generates the feed XML file once and stores it as a static asset to serve as `https://join-lemmy.org/feed.xml`
I hope this is useful and we can get it merged. Let me know if you have any feedback to get this merged.

Generate RSS feed from markdown news

---

src/shared/components/app-definitions.ts

Hi! I noticed that https://join-lemmy.org/apps was referencing an [old Dart client from LemmurOrg](https://github.com/LemmurOrg/lemmy_api_client) which was archived in Feb 2023. That client was [forked](https://github.com/liftoff-app/lemmy_api_client/) and maintained by a while by the developer(s) of Liftoff, but that also appears to have gone dead (no updates in 6 months, no support for Lemmy 0.19.x). Over at Thunder, we have made [yet another fork](https://github.com/thunder-app/lemmy_api_client) and are actively maintaining it, which we think would make a good addition to the site.
Tagging @hjiangsu, the primary maintainer!

Use the Thunder team's Dart client

---

src/server/index.tsx

Try pasting the following into the editor at https://json-ld.org/playground/
```
{
"@context": [
"https://www.w3.org/ns/activitystreams",
"https://join-lemmy.org/context.json"
],
"id": "https://enterprise.lemmy.ml/post/55143",
"type": "Page",
"audience": "https://enterprise.lemmy.ml/c/tenforward",
"name": "Post title",
"content": "<p>This is a post in the /c/tenforward community</p>\n",
"tag": [
{
"type": "lemmy:CommunityPostTag",
"id": "https://enterprise.lemmy.ml/c/tenforward/tag/news",
"name": "News"
}
]
}
```
You will get this error: 
Allowing CORS here seems harmless and makes it easier to verify whether Lemmy AP objects  are interpreted correctly and valid.

Add CORS header to context.json for JSON-LD playground to work

---

recommended-instances.json

- lemmy.fmhy.ml is long dead since their domain was taken away
- feddit.de died a while back, feddit.org is its spiritual successor

Update instance crawler start instances

---

src/shared/components/app-definitions.ts

The Eternity client is no longer available on the IzzyOnDroid repository and is now on the main F-Droid repo instead. 
See https://apt.izzysoft.de/fdroid/index/apk/eu.toldi.infinityforlemmy

Update F-Droid link for Eternity client

---

renovate.json

This way we can avoid problems such as https://github.com/LemmyNet/joinlemmy-site/issues/431. Anyway there is no reason to use latest library versions other than security.
https://docs.renovatebot.com/presets-security/#securityonly-security-updates

Renovate should only apply security updates
